name: clarifi
description: Una app de finanzas personales con Flutter y Firebase
publish_to: 'none' # evita que se publique en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase y utilidades
  firebase_core: 
  firebase_auth: 
  cloud_firestore: 
  google_sign_in: ^7.1.1 
  intl: 
  flutter_localizations:
    sdk: flutter
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
